### ISSUE TITLE
version bump

### ISSUE THREAD

**Issue by lei0zhou** [RatioPBC/epi-viewpoint#16]
## context
Update Elixir and libraries, Erlang, Postgres to the latest stable release version

## version bump target
- [x] Elixir 1.17
- [x] Erlang/OTP 27
- [x] Postgres 16
- [x] Phoenix 1.7
- [x] Liveview 1.0.0
- [x] Ecto 3.11
- [x] update .tool-versions

## acceptance criteria
- [x] deps updated accordingly
- [x] Make all the tests pass

## note
~current unresolved warnings (use <.link>) will be addressed in another ticket #20, since it is a scoped issue and need further refactoring~

~CI currently failed due to setting "--warnings-as-errors" : Lei plan to remove --warnings-as-errors to make CI pass, and will resolve in the next pr and add "--warnings-as-errors" back~

## ref
- [phoenixframework/phoenix_html_helpers: Collection of helpers to generate and manipulate HTML contents](https://github.com/phoenixframework/phoenix_html_helpers)

**Comment by lei0zhou** [comment]
@jc00ke , two questions
- as mentioned in the note above, do you think that approach make sense?
- we add support for postgres 17, set continue on error, does the ci process make sense, the docker pull failed and stopped there,  do I need to change anything regarding that?

**Comment by jc00ke** [comment]
Sounds good to me, Lei. Please proceed with #20 and removing the `--warnings-as-errors` for now.

**Comment by jc00ke** [comment]
Re: pg17, if the Docker pull failed, then don't spend any time on it now and we can look into it later.

**Comment by lei0zhou** [comment]
> Sounds good to me, Lei. Please proceed with #20 and removing the `--warnings-as-errors` for now.

#20 is addressed in this pr and all tests passed without warnings
